require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'WiseTooth' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'GoogleUtilities', :modular_headers => true;
  pod 'FirebaseCore', :modular_headers => true



  target 'WiseToothTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.95.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'WiseTooth-tvOS' do
  # Pods for WiseTooth-tvOS

  target 'WiseTooth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
